export enum AccionesEnum {
  CREAR_IIPP = 'CREAR_IIPP',
  EDITAR_IIPP = 'EDITAR_IIPP',

  // para roles
  CREAR = 'CREAR',
  EDITAR = 'EDITAR',
  ELIMINAR = 'ELIMINAR',
  ANULAR = 'ANULAR',
  DESHABILITAR = 'DESHABILITAR',
  CONFIRMAR = 'CONFIRMAR',
  CANCELAR = 'CANCELAR',
  CONCILIAR = 'CONCILIAR',
  GENERAR = 'GENERAR',
  SUBIR_ARCHIVO = 'SUBIR_ARCHIVO',
  OPERACION = 'OPERACION',
  TRANSFERENCIA = 'TRANSFERENCIA',
  ERRORES = 'ERRORES',
  ADVERTENCIAS = 'ADVERTENCIAS',
  DETALLE = 'DETALLE', // Para ver toda la informacion de una entidad especifica
  REGISTRAR = 'REGISTRAR',
  CARGAR = 'CARGAR',
  NOTIFICAR = 'NOTIFICAR',
  GESTIONAR = 'GESTIONAR',
  FINALIZAR = 'FINALIZAR',
  LISTAR = 'LISTAR', // Para mostrar todos los datos de una entidad, ej: Bandejas
  EMBARGAR = 'EMBARGAR'
}
