export enum RoleIdEnum {
  MC_CUSTODIA_ANALISTA_FUNCIONAL = 'MC_CUSTODIA_ANALISTA_FUNCIONAL',
  MC_CUSTODIA_GESTION_COMERCIAL = 'MC_CUSTODIA_GESTION_COMERCIAL',
  MC_CUSTODIA_GESTION_OPERACION = 'MC_CUSTODIA_GESTION_OPERACION',
  MC_CUSTODIA_CONSULTA = 'MC_CUSTODIA_CONSULTA'
}
