export enum RoleIdEnum {
  RCT_LEGALES_DEV = 'RCT_LEGALES_DEV',
  RCT_ADMINISTRADOR_DEV = 'RCT_ADMINISTRADOR_DEV',
  RCT_CONSULTA_DEV = 'RCT_CONSULTA_DEV',
  RCT_ADMINISTRADOR = 'RCT_ADMINISTRADOR',
  RCT_CONSULTA = 'RCT_CONSULTA',
  RCT_LEGALES = 'RCT_LEGALES'
}
